Repository alx3416/tallerGit2, pull requests merged in 2024-01, with the labels that each got.

#1 Revert "Update main.py"
  main.py
Labels: bug

#5 Feature/area circulo
  TrashZAC.txt
  area_circulo.txt
  main.py
  main2.py
Labels: enhancement, good first issue

#4 P circulo
  main.py
Labels: good first issue
